volumes:
  postgres_data_cinema:
    driver: local

services:
  postgres_cinema:
    container_name: postgres_cinema
    image: postgres:15
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:      
      - postgres_data_cinema:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin_cinema:
    container_name: pgadmin_cinema
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}
    depends_on:
      - postgres_cinema
    restart: unless-stopped
  redis_cinema:
    container_name: redis_cinema
    image: redis:8-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      